name: Deploy GitHub Pages (gh-pages)

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1

      - name: Rebuild pages/songs.json from lyrics
        run: |
          mkdir -p pages
          deno cache ./txt2json-all.ts
          deno run --allow-read=lyrics --allow-net ./txt2json-all.ts > pages/songs.json

      - name: Validate pages/songs.json
        run: python3 -c "import json,sys; json.load(open('pages/songs.json'))"

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pages
          publish_branch: gh-pages
          allow_empty_commit: true
