name: Release songs archive

on:
  push:
    branches:
      - master

jobs:
  zip-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate version
        run: |
          echo "VERSION=$(TZ='Europe/Prague' date +'%y%m%dT%H%M')" >> $GITHUB_ENV

      - name: Generate artifact name
        run: |
          echo "ARTIFACT=songs-v${{ env.VERSION }}.zip" >> $GITHUB_ENV

      - name: Archive
        run: |
          zip -r -UN=UTF8 ${{ env.ARTIFACT }} Songs >/dev/null

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.ARTIFACT }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "songs-v${{ env.VERSION }}"
          name: "Songs v${{ env.VERSION }}"
          body: "The release contains zip-archived Songs folder."
          draft: false
          prerelease: false

  build-and-release-tools:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Compile tools
        run: |
          deno compile --allow-all --target x86_64-pc-windows-msvc --output update-songs.exe update-songs.ts

      - name: Upload executable tools
        uses: actions/upload-artifact@v3
        with:
          name: update-songs
          path: update-songs.exe
