name: Release songs archive and text

on:
  push:
    branches:
      - master

jobs:
  zip-and-release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Generate version
        run: |
          echo "VERSION=$(TZ='Europe/Prague' date +'%y%m%dT%H%M')" >> $GITHUB_ENV

      - name: Generate artifact names
        run: |
          echo "XML_ARTIFACT=songs-v${{ env.VERSION }}.zip" >> $GITHUB_ENV
          # TODO: Re-enable TXT artifact in the future
          # echo "TXT_ARTIFACT=songs-v${{ env.VERSION }}.txt" >> $GITHUB_ENV

      - name: Build songs to OS format
        run: |
          mkdir -p build/Songs
          deno run -A text2xml.ts songs-text/ build/Songs/

      - name: Archive
        run: |
          cd build
          zip -r -UN=UTF8 ${{ env.XML_ARTIFACT }} Songs >/dev/null
          cd ..

      # TODO: Re-enable TXT export in the future
      # - name: Export songs into single text file
      #   run: |
      #     deno run -A serialize.ts 'songs-text/*.txt' '<<<' "build/${{ env.TXT_ARTIFACT }}"

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/${{ env.XML_ARTIFACT }}
            # TODO: Re-enable TXT artifact in the future
            # build/${{ env.TXT_ARTIFACT }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "songs-v${{ env.VERSION }}"
          name: "Songs v${{ env.VERSION }}"
          body: "The release contains zip-archived Songs folder."
          draft: false
          prerelease: false

  build-and-release-tools:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Compile tools
        run: |
          deno compile --allow-all --target x86_64-pc-windows-msvc --output update-songs.exe update-songs.ts

      - name: Upload executable tools
        uses: actions/upload-artifact@v4
        with:
          name: update-songs
          path: update-songs.exe
